# Generated by Django 5.2.7 on 2026-05-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('actor', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
            ],
            options={
                'db_table': 'activity',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('order_type', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=200, null=True)),
                ('turnboy_id', models.IntegerField(blank=True, null=True)),
                ('turnboy_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('driver_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('turnboy_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=300, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deliveries',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='units', max_length=50)),
                ('min_stock_level', models.IntegerField(default=0)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_low_stock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('litres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bottle_count', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_location', models.CharField(blank=True, max_length=300, null=True)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=200, null=True)),
                ('turnboy_id', models.IntegerField(blank=True, null=True)),
                ('turnboy_name', models.CharField(blank=True, max_length=200, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.IntegerField(blank=True, null=True)),
                ('worker_name', models.CharField(max_length=200)),
                ('worker_role', models.CharField(blank=True, max_length=50, null=True)),
                ('period_date', models.DateField()),
                ('base_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('penalties', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('deliveries_count', models.IntegerField(default=0)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('adjustments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payroll',
                'ordering': ['-period_date', 'worker_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('related_order_id', models.IntegerField(blank=True, null=True)),
                ('related_worker_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_assigned', models.CharField(blank=True, max_length=200, null=True)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workers',
                'ordering': ['name'],
                'managed': True,
            },
        ),
    ]
